default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/prelaunchr_development.sqlite3

test:
  <<: *default
  database: db/prelaunchr_test.sqlite3

production:
  <<: *default
  database: db/prelaunchr_production.sqlite3